### PR TITLE
Removed PHP

### PR DESCRIPTION
**Pull request by codedust**
Hi there!

I really like the idea behind this Studi-Mat and therefore would like to contribute some improvements. ;)

I thought it would be a good idea to get rid of the PHP code since it is not really needed. The ultimate goal was/is to be able to change the language without reloading the page. This already works for most parts of the UI.

My changes in detail:
- removed PHP (except "include '_tracking.php';")
- csv data is now parsed via PapaParse (http://papaparse.com/, MIT
  license)
- the language is now selected client-side via Javscript (URL parameter
  and cookie detection)
- supports changing the language without reloading the page (exept the
  question texts) via 'helper.updateLanguage(lang["en"]);'. Currently,
  the page is reloaded in order to update these texts.
- some more minor fixes (mostly formatting and spelling)

Sorry for the huge commit. I hope that's OK.

### CODE REVIEW

**Comment by openpaul** [comment]
Hi,
thanks for taking an interest in the studi-mat.
I took a look at the changes and it looks nice.

Removing PHP is a good idea. While looking at your branch I found that the HTML is slightly broken. The text of the statements should be separated after the first paragraph, so the first paragraph can be displayed bigger then the following, which are used as an explanation to the statement (left: current, right yours):
comparison

If you change this, I would merge the code (after the elections are over), as the changes look really usefull to me.

Thank you once again. If you're interested in working further on this project just contact me or the AStA of the TU Darmstadt
Or keep submitting nice code ;-)

**Comment by codedust** [comment]
Fixed it. (I fixed it the same way the PHP code did it before (feels ugly). Maybe it would be a good idea to get rid of the global "daten" variable.)

**Comment by openpaul** [comment]
Yes, the way it is done is ugly. Maybe the csv should just contain two colums: One with the Statement and one with the explanation.
This way the data object would be more pretty.

Moreover the daten variable should not be global, but only passed to the function who need it. But thats another story for another day

**Comment by codedust** [comment]
Yep, using two columns seems to be a good idea.

**Pull request merged**
